### ISSUE TITLE
Underscore/hyphen issues

### ISSUE THREAD

**Issue by bollwyvl** [conda-forge/email-validator-feedstock#3]
I was just building something that uses `airflow`, and saw that this and its underscore-ful namesake both got installed, throwing a bunch of clobber warnings. since they are both definitely being used, I guess we're stuck with it.
 
It would be lovely if either this or the other  feedstock was archived, and stopped creating releases, and one of them became a noop... 

prior art:
- https://github.com/conda-forge/importlib_metadata-feedstock

**Comment by xylar** [comment]
@ocefpaf, I created this awhile ago not realizing there's already the same feedstock with an underscore instead: https://github.com/conda-forge/email_validator-feedstock.

I don't seem to have permission to archive this one.  Could you?

**Comment by xylar** [comment]
@bollwyvl, thanks for the tip and sorry for the trouble.  I'll take care of this.

**Comment by ocefpaf** [comment]
Sure. Archiving it. Thanks both of you for taking care of this!

**Comment by xylar** [comment]
Thanks a lot, @ocefpaf!

**Comment by bollwyvl** [comment]
Thanks again!
